sudo: false
before_install:
 - chmod +x gradlew
 - android create avd --force -n test -t android-25 --abi armeabi-v7a
 - emulator -avd test -no-skin -no-audio -no-window &
 - android-wait-for-emulator
 - adb shell input keyevent 82 &
language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.0
    - sys-img-armeabi-v7a-addon-google_apis-google-25

    # The SDK version used to compile your project
    - android-25
  licenses:
    - 'android-sdk-license-.+'

