sudo: false
before_install:
 - chmod +x gradlew

language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.0
    - sys-img-armeabi-v7a-addon-google_apis-google-25

    # The SDK version used to compile your project
    - android-25
  licenses:
    - 'android-sdk-license-.+'

